name: challenge_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  database_client: any
  flutter:
    sdk: flutter
  powersync_repository: any
  rxdart: ^0.28.0
  shared: any
  user_repository: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
