name: shared
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  app_ui:
    path: ../app_ui
  env:
    path: ../env
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  intl: ">=0.18.0 <=0.20.2"
  jiffy: ^6.3.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  meta: any
  powersync: ^1.11.2
  user_repository:
    path: ../user_repository
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
