name: supabase_authentication_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

dependencies:
  authentication_client:
    path: ../authentication_client
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.2
  powersync_repository:
    path: ../../powersync_repository
  supabase_flutter: ^2.8.3
  token_storage:
    path: ../token_storage
