name: user_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.22.0

dependencies:
  authentication_client:
    path: ../authentication_client/authentication_client
  database_client:
    path: ../database_client
  flutter:
    sdk: flutter
  powersync_repository:
    path: ../powersync_repository
  rxdart: ^0.27.7
  shared:
    path: ../shared

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
