name: user_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.22.0

dependencies:
  authentication_client: any
  database_client: any
  flutter:
    sdk: flutter
  powersync_repository: any
  rxdart: ^0.28.0
  shared: any

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
