name: daikoon_workspace
packages:
  - packages/*
  - packages/*/*

scripts:
  build_runner:
    run: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner

  test:
    run: flutter test --coverage
    packageFilters:
      dirExists: test

command:
  bootstrap:
    usePubspecOverrides: true
    runPubGetInParallel: false

dependency_overrides:
  database_client:
    path: packages/database_client
