name: daikoon
description: A Very Good Project created by Very Good CLI.
version: 1.0.1+26
publish_to: none

workspace:
  - packages/app_ui
  - packages/authentication_client/authentication_client
  - packages/authentication_client/supabase_authentication_client
  - packages/authentication_client/token_storage
  - packages/challenge_repository
  - packages/daikoon_blocks_ui
  - packages/database_client
  - packages/env
  - packages/form_fields
  - packages/notifications_client/firebase_notifications_client
  - packages/notifications_client/notifications_client
  - packages/notifications_repository
  - packages/powersync_repository
  - packages/shared
  - packages/user_repository

environment:
  sdk: ^3.5.0

dependencies:
  animations: ^2.0.11
  app_ui: any
  authentication_client: any
  bloc: ^9.0.0
  challenge_repository: any
  collection: ^1.19.0
  daikoon_blocks_ui: any
  database_client: any
  env: any
  equatable: ^2.0.7
  firebase_core: ^3.12.1
  firebase_notifications_client: any
  flex_color_scheme: ^8.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  form_fields: any
  get_it: ^8.0.3
  go_router: ^14.8.1
  google_sign_in: ^6.2.2
  intl: ^0.19.0
  notifications_repository: any
  powersync_repository: any
  shared: any
  sliver_tools: ^0.2.12
  supabase_authentication_client: any
  token_storage: any
  user_repository: any

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  build_verify: ^3.1.0
  flutter_test:
    sdk: flutter
  melos: ^7.0.0-dev.7
  mockito: ^5.4.5
  mocktail: ^1.0.4
  rxdart: ^0.27.7
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true

melos:
  scripts:
    build_runner:
      run: melos exec dart run build_runner build --delete-conflicting-outputs
      packageFilters:
        dependsOn: build_runner

    test:
      run: flutter test --coverage
      packageFilters:
        dirExists: test
