name: daikoon
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  animations: ^2.0.11
  app_ui:
    path: packages/app_ui
  bloc: ^9.0.0
  env:
    path: packages/env
  equatable: ^2.0.7
  firebase_core: ^3.10.1
  flex_color_scheme: ^8.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  form_fields:
    path: packages/form_fields
  get_it: ^8.0.3
  go_router: ^14.7.2
  google_sign_in: ^6.2.2
  intl: ^0.19.0
  powersync_repository:
    path: packages/powersync_repository
  shared:
    path: packages/shared
  sliver_tools: ^0.2.12
  supabase_authentication_client:
    path: packages/authentication_client/supabase_authentication_client
  token_storage:
    path: packages/authentication_client/token_storage
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.14
  build_verify: ^3.1.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  mocktail: ^1.0.4
  rxdart: ^0.27.7
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
