// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDHMZsf781MyZlpm4Tcb-WlAVNeE-AOVs',
    appId: '1:49085509221:android:904092f005960ae601e08c',
    messagingSenderId: '49085509221',
    projectId: 'daikoon-prod',
    storageBucket: 'daikoon-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0xjfQ3WYzeRrPC5f76fjokTH3aUfIcBQ',
    appId: '1:49085509221:ios:d5f6a3fee2f2ee7001e08c',
    messagingSenderId: '49085509221',
    projectId: 'daikoon-prod',
    storageBucket: 'daikoon-prod.firebasestorage.app',
    iosClientId:
        '49085509221-csmvuvobc4b0tpdpo6tljvlcveuf7rk8.apps.googleusercontent.com',
    iosBundleId: 'dev.llanas.daikoon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0xjfQ3WYzeRrPC5f76fjokTH3aUfIcBQ',
    appId: '1:49085509221:ios:d5f6a3fee2f2ee7001e08c',
    messagingSenderId: '49085509221',
    projectId: 'daikoon-prod',
    storageBucket: 'daikoon-prod.firebasestorage.app',
    iosClientId:
        '49085509221-csmvuvobc4b0tpdpo6tljvlcveuf7rk8.apps.googleusercontent.com',
    iosBundleId: 'dev.llanas.daikoon',
  );
}
