// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt3mp684W518WZZ55eHPD2zRK-PRom0_k',
    appId: '1:516409268825:android:015a8a544254fbcc5e2f48',
    messagingSenderId: '516409268825',
    projectId: 'daikoon-dev',
    storageBucket: 'daikoon-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClJIKueocGQy8yQVaoN_cletCRzv6a8qM',
    appId: '1:516409268825:ios:8b022b41b73b0b5d5e2f48',
    messagingSenderId: '516409268825',
    projectId: 'daikoon-dev',
    storageBucket: 'daikoon-dev.firebasestorage.app',
    iosClientId:
        '516409268825-8rrkamt4e9chds1qghv7i9pu95em6iut.apps.googleusercontent.com',
    iosBundleId: 'dev.llanas.daikoon.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClJIKueocGQy8yQVaoN_cletCRzv6a8qM',
    appId: '1:516409268825:ios:8b022b41b73b0b5d5e2f48',
    messagingSenderId: '516409268825',
    projectId: 'daikoon-dev',
    storageBucket: 'daikoon-dev.firebasestorage.app',
    iosClientId:
        '516409268825-8rrkamt4e9chds1qghv7i9pu95em6iut.apps.googleusercontent.com',
    iosBundleId: 'dev.llanas.daikoon.dev',
  );
}
