name: form_fields
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.7.2
  flutter: ^3.22.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  formz: ^0.4.1
