# Define sync rules to control which data is synced to each user
# See the docs: https://docs.powersync.com/usage/sync-rules
bucket_definitions:
  global_challenges:
    data:
      - select * from bets
      - select * from challenges
      - select * from choices
      - select *, challenge_id || '.' || user_id as id from participants

  global_users:
    data:
      - select * from users
      - select *, sender_id || '.' || receiver_id as id from friendships
      - select * from notifications

  global_wallets:
    data:
      - select *, user_id as id from wallets
      - select * from transactions
