# yaml-language-server: $schema=https://unpkg.com/@powersync/service-sync-rules@latest/schema/sync_rules.json
#
# See Documentation for more information:
# https://docs.powersync.com/usage/sync-rules
#
# Note that changes to this file are not watched.
# The service needs to be restarted for changes to take effect.

bucket_definitions:
  global_challenges:
    data:
      - select * from bets
      - select * from challenges
      - select * from choices
      - select * from participants

  global_users:
    data:
      - select * from users
      - select * from friendships
      - select * from notifications

  global_wallets:
    data:
      - select * from wallets
      - select * from transactions
