name: daikoon_blocks_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  app_ui: any
  flutter:
    sdk: flutter
  intl: ^0.19.0
  shared: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
